name: latexify-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.7.2=h166bdaf_0
  - aom=3.4.0=h27087fc_1
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.14=ha878542_0
  - cairo=1.16.0=ha61ee94_1013
  - certifi=2022.9.14=pyhd8ed1ab_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.6=h5008d03_3
  - expat=2.4.9=h27087fc_0
  - ffmpeg=4.4.2=gpl_hfe78399_107
  - fftw=3.3.10=nompi_hf0379b8_105
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=hca18f0e_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h7b6447c_0
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.7=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.20.3=h57caac4_1
  - gstreamer=1.20.3=hd4edc92_1
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jack=1.9.18=h8c3723f_1003
  - jasper=2.0.33=ha77e612_0
  - jpeg=9e=h7f8727e_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libcap=2.65=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_hc1a23ef_0
  - libclang13=14.0.6=default_h31cde19_0
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.113=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.6.0=py310hcb97b83_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libpq=14.5=hd77ab85_0
  - libprotobuf=3.20.1=h6239696_4
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsqlite=3.39.3=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.4.0=hecacb30_0
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mysql-common=8.0.30=haf5c9bc_1
  - mysql-libs=8.0.30=h28c427c_1
  - ncurses=6.3=h5eee18b_3
  - nettle=3.8.1=hc379101_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.1=py310h1794996_0
  - numpy-base=1.23.1=py310hcba007f_0
  - opencv=4.6.0=py310hff52083_0
  - openh264=2.3.0=h27087fc_0
  - openssl=1.1.1q=h166bdaf_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.2.0=py310hace64e9_1
  - pip=22.1.2=py310h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - portaudio=19.6.0=h8e90077_6
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=14.0=h0868958_9
  - py-opencv=4.6.0=py310hfdc917e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.6=h582c2e5_0_cpython
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - qt-main=5.15.6=hc525480_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py310h06a4308_0
  - setuptools=63.4.1=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - svt-av1=1.2.1=h27087fc_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py310_cu113
  - torchvision=0.13.1=py310_cu113
  - typing_extensions=4.3.0=py310h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.11=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - anyio==3.6.1
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - bcrypt==4.0.0
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - entrypoints==0.4
    - executing==1.0.0
    - fonttools==4.37.1
    - gradio==3.4.0
    - ipykernel==6.15.2
    - ipython==8.4.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - nest-asyncio==1.5.5
    - packaging==21.3
    - pandas==1.4.4
    - paramiko==2.11.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.30
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pydantic==1.10.2
    - pygments==2.13.0
    - pynacl==1.5.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - pyzmq==23.2.1
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - sniffio==1.2.0
    - stack-data==0.5.0
    - threadpoolctl==3.1.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.3.0
    - wcwidth==0.2.5
